### ISSUE TITLE
[Bug]: pyvene.ai is taking too long to respond

### ISSUE THREAD

**Issue by pravintargaryen** [stanfordnlp/pyvene#134]
### Contact Details

pravinmd94@gmail.com

### What happened?

Receiving error message when visiting "Pyvene.ai" website. The message says the site can't be reached at the moment. It's taking too long to respond.

### Code to produce this issue.

```shell
Visit https://pyvene.ai/ in Browser

Chrome : Version 123.0.6312.58 (Official Build) (64-bit)
OS : Win10 Pro for Workstations
```

**Comment by frankaging** [comment]
Hey! Thanks for letting us know! At this moment `pyvene.ai` is not ready yet - for now, it is a dummy redirection to this repo (even if it works)!

We are building the website `pyvene.ai`, and we will release with other features once they are ready!

**Comment by frankaging** [comment]
minor: I also removed the reference link to `pyvene.ai` for now to avoid confusion. I linked our paper instead! Before `pyvene.ai` website is ready, feel free to read our paper to know more about the library!
