### ISSUE TITLE
[P2] Sparse autoencoders

### ISSUE THREAD

**Issue by aryamanarora** [stanfordnlp/pyvene#77]
We should add support for training sparse autoencoders ([Bricken et al., 2023](https://transformer-circuits.pub/2023/monosemantic-features#setup-autoencoder-motivation), [Cunningham et al., 2023](https://arxiv.org/abs/2309.08600)). Cool be cool as a way of obtaining a feature basis for interventions.

**Comment by frankaging** [comment]
@explanare has this locally setup I think.

**Comment by smejak** [comment]
What functionality should this PR have for best integration with existing pyvene tools?
I have an implementation of SAE training working with transformerlens models (largely inspired by [Neel Nanda’s code](https://github.com/neelnanda-io/1L-Sparse-Autoencoder/tree/main) but adjusted such that experiments are easier to modify). Currently the Buffer class collects the activations from a layer with the `model.run_with_cache` function, I presume there is an equivalent pyvene function that should be used instead? Other than that I think all the other code should currently be interoperable with pyvene.

**Comment by frankaging** [comment]
@smejak currently, pyvene supports activation collection as in the first two examples in https://github.com/stanfordnlp/pyvene/blob/main/pyvene_101.ipynb. Will this help?
