### ISSUE TITLE
[P0] Upgrade tutorials to new API 

### ISSUE THREAD

**Issue by aryamanarora** [stanfordnlp/pyvene#86]
A lot of the old tutorials are using the old API for representation configs and interventions; some of them might even be broken because of this. We should upgrade all of them to the new format to showcase how the library is designed to be used. Thanks to @smejak for pointing this out.

Edit: Specifically, intro DAS tutorial isn't working in colab, intervened forward pass is failing. Will debug this later today.

**Comment by frankaging** [comment]
Closing this issue for now, as i tested on new ToT with Main DAS tutorial with CPU on colab, and it works fine now! Please feel free to open other issues for tutorials if it appears again.

Thanks!
